services:
  api-gateway:
    build:
      context: ./backend/api-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - CRAWLEE_SERVICE_URL=http://crawlee-service:3001
      - LIGHTHOUSE_SERVICE_URL=http://lighthouse-service:3002
      - SEO_SERVICE_URL=http://seo-service:3003
    restart: unless-stopped
    networks:
      - seo_network

  crawlee-service:
    build:
      context: ./backend/crawlee-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - seo_network

  lighthouse-service:
    build:
      context: ./backend/lighthouse-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - seo_network

  seo-service:
    build:
      context: ./backend/seo-audit-service
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - seo_network

networks:
  seo_network:
    driver: bridge
