services:
  - type: web
    name: seo-audit-api-gateway
    env: node
    repo: https://github.com/magekt/universal-seo-audit-service
    buildCommand: cd backend/api-gateway && npm ci --only=production
    startCommand: cd backend/api-gateway && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: CRAWLEE_SERVICE_URL
        value: https://seo-audit-crawlee.onrender.com
      - key: LIGHTHOUSE_SERVICE_URL
        value: https://seo-audit-lighthouse.onrender.com
      - key: SEO_SERVICE_URL
        value: https://seo-audit-seo.onrender.com
    plan: free
    region: oregon

  - type: web
    name: seo-audit-crawlee
    env: node
    repo: https://github.com/magekt/universal-seo-audit-service
    buildCommand: cd backend/crawlee-service && npm ci --only=production
    startCommand: cd backend/crawlee-service && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: MAX_PAGES
        value: "25"
      - key: CONCURRENCY
        value: "1"
    plan: free
    region: oregon

  - type: web
    name: seo-audit-lighthouse
    env: node
    repo: https://github.com/magekt/universal-seo-audit-service
    buildCommand: cd backend/lighthouse-service && npm ci --only=production
    startCommand: cd backend/lighthouse-service && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
    plan: free
    region: oregon

  - type: web
    name: seo-audit-seo
    env: node
    repo: https://github.com/magekt/universal-seo-audit-service
    buildCommand: cd backend/seo-audit-service && npm ci --only=production
    startCommand: cd backend/seo-audit-service && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
    plan: free
    region: oregon

  - type: web
    name: seo-audit-frontend
    env: static
    repo: https://github.com/magekt/universal-seo-audit-service
    buildCommand: cd frontend && npm ci && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://seo-audit-api-gateway.onrender.com/api
    plan: free
    region: oregon
